PD-197980: revise backstage system information
bazaarvoice/astyanax pull request #29
Opened 2023-01-03 08:33 UTC by SergiiKryvenko

## Jira Issue #

[PD-197980](https://bazaarvoice.atlassian.net/browse/PD-197980)

## What Are We Doing Here?

Add/revise information about components on [the Bаckstage system](https://backstage.prod.bazaarvoice.com/catalog/default/component/).

## How to Test and Verify

1. Check out this PR
2. Check if the info on [the Bаckstage system](https://backstage.prod.bazaarvoice.com/catalog/default/component/) displays correctly: astyanax

## Risk

### Level

`Low`

### Required Testing

`Smoke`

### Risk Summary

## Code Review Checklist

- [ ] Testing instructions are included. If not, make sure you leave us a line or two for the reason.

- [ ] Well documented, including updates to any necessary markdown files. When
  we inevitably come back to this code it will only take hours to figure out, not
  days.

- [ ] Make sure PR has only the changes required for the Jira issues.

- [ ] Have someone from a different region than you review your changes. If not, make sure to leave a comment on why it is not required

- [ ] If it's applicable, document the deployment plan for the changes.

2023-01-03 12:22 UTC, mike-unitskyi requested changes
looks good

2023-01-03 12:22 UTC, mike-unitskyi commented on catalog-info.yaml
> +    - jackson
```suggestion
    - thrift
```

2023-01-03 14:29 UTC, SergiiKryvenko commented on catalog-info.yaml
> +    - jackson
done

2023-01-04 12:22 UTC, mike-unitskyi approved these changes

2023-01-04 12:24 UTC, merged